// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'menu-settings'
  | 'menu-tasks'
  | 'menu-tools-submenu'
  | 'menu-translate';
