// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "command": string;
      "langIn": string;
      "langOut": string;
      "openaiBaseURL": string;
      "openaiBaseURLRoot": string;
      "openaiBaseURLSuffixPreset": string;
      "openaiBaseURLSuffixCustom": string;
      "openaiModel": string;
      "openaiApiKey": string;
      "customSystemPrompt": string;
      "extraArgs": string;
      "qps": string;
      "requestRetryCount": string;
      "outputRoot": string;
      "openResult": boolean;
      "confirmBeforeStart": boolean;
      "dualTranslateFirst": boolean;
      "useAlternatingPagesDual": boolean;
      "skipClean": boolean;
      "disableRichTextTranslate": boolean;
      "watermarkOutputMode": string;
      "keepOutputFiles": boolean;
      "autoExtractGlossary": boolean;
    };
  }
}
